
            @startuml hello
            class File {
                + name: String
                + size: int
            }

            class Summary {
                + data: String
                + visualize(): void
            }

            File -- Summary : Contains
            @enduml
            